### ISSUE TITLE
ModuleNotFoundError: No module named 'interface'

### ISSUE THREAD

**Issue by dalealleshouse** [nhfruchter/pgh-bustime#2]
I get the following error when i try to use pgh-bustime after installing it via pip

```
Traceback (most recent call last):
  File "C:\src\phg-bus-tracker\bus-tracker.py", line 1, in <module>
    from pghbustime import *
  File "C:\Program Files\Python36\lib\site-packages\pghbustime\__init__.py", line 1, in <module>
    from interface import BustimeAPI
ModuleNotFoundError: No module named 'interface'
Press any key to continue . . .
```

I cloned your repo and I get the same thing when I attempt to run the tests

**Comment by ulfmagnetics** [comment]
Looks like some minor changes are needed in order to support the [changes to imports](https://stackoverflow.com/a/12173406/1018959)  in Python 3. I have this working fine with Python 2.7 if that's an option for you.

**Comment by jaredcoh** [comment]
Thank you for letting me know! I'll take a look at the imports to determine how they can be changed to fit Py3 but because I am stuck on Python 3 for some other projects I'm looking to integrate this into, I'll have to manually modify it, thank you though!
